export const data_json = [
  {
    id: 1,
    title: "Pembersih",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 1,
        id_kategori: 1,
        kategori: "Pembersih Rumah",
        item: "Sapu Ijuk",
        lowest_price: "Rp12.500",
        highest_price: "Rp50.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 2,
        id_kategori: 1,
        kategori: "Pembersih Rumah",
        item: "Pengki",
        lowest_price: "Rp11.000",
        highest_price: "Rp44.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 3,
        id_kategori: 1,
        kategori: "Pembersih Rumah",
        item: "Kemoceng",
        lowest_price: "Rp5.000",
        highest_price: "Rp20.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 4,
        id_kategori: 1,
        kategori: "Pembersih Rumah",
        item: "Sapu Lidi",
        lowest_price: "Rp10.000",
        highest_price: "Rp40.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 5,
        id_kategori: 1,
        kategori: "Pembersih Rumah",
        item: "Sikat",
        lowest_price: "Rp3.000",
        highest_price: "Rp12.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 6,
        id_kategori: 1,
        kategori: "Pembersih Rumah",
        item: "Kain Pel",
        lowest_price: "Rp5.000",
        highest_price: "Rp20.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 7,
        id_kategori: 1,
        kategori: "Pembersih Rumah",
        item: "Tong Sampah",
        lowest_price: "Rp60.000",
        highest_price: "Rp240.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 8,
        id_kategori: 1,
        kategori: "Pembersih Rumah",
        item: "Kanebo",
        lowest_price: "Rp10.000",
        highest_price: "Rp40.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 2,
    title: "Tools Umum",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 9,
        id_kategori: 2,
        kategori: "Tools Umum",
        item: "Set Kunci L",
        lowest_price: "Rp18.000",
        highest_price: "Rp72.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 10,
        id_kategori: 2,
        kategori: "Tools Umum",
        item: "Set Kunci Sok",
        lowest_price: "Rp85.000",
        highest_price: "Rp340.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 11,
        id_kategori: 2,
        kategori: "Tools Umum",
        item: "Ring / Pas 12-14",
        lowest_price: "Rp14.000",
        highest_price: "Rp56.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 12,
        id_kategori: 2,
        kategori: "Tools Umum",
        item: "Ring / Pas 8-10",
        lowest_price: "Rp27.000",
        highest_price: "Rp104.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 13,
        id_kategori: 2,
        kategori: "Tools Umum",
        item: "Ring / Pas 17-19",
        lowest_price: "Rp40.000",
        highest_price: "Rp160.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 14,
        id_kategori: 2,
        kategori: "Tools Umum",
        item: "Kunci Busi",
        lowest_price: "Rp19.000",
        highest_price: "Rp76.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 15,
        id_kategori: 2,
        kategori: "Tools Umum",
        item: "Obeng +",
        lowest_price: "Rp24.000",
        highest_price: "Rp96.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 16,
        id_kategori: 2,
        kategori: "Tools Umum",
        item: "Obeng -",
        lowest_price: "Rp24.000",
        highest_price: "Rp96.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 17,
        id_kategori: 2,
        kategori: "Tools Umum",
        item: "Tang",
        lowest_price: "Rp30.000",
        highest_price: "Rp116.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 18,
        id_kategori: 2,
        kategori: "Tools Umum",
        item: "Set Kunci Sok",
        lowest_price: "Rp85.000",
        highest_price: "Rp340.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 19,
        id_kategori: 2,
        kategori: "Tools Umum",
        item: "Traker / Kunci Pully",
        lowest_price: "Rp50.000",
        highest_price: "Rp200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 20,
        id_kategori: 2,
        kategori: "Tools Umum",
        item: "Traker Penahan Pully",
        lowest_price: "Rp50.000",
        highest_price: "Rp200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 3,
    title: "Alat Dapur",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 21,
        id_kategori: 3,
        kategori: "Alat Dapur",
        item: "Set Pisau",
        lowest_price: "Rp30.000",
        highest_price: "Rp120.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 22,
        id_kategori: 3,
        kategori: "Alat Dapur",
        item: "Sendok & Garpu",
        lowest_price: "Rp12.000",
        highest_price: "Rp48.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 23,
        id_kategori: 3,
        kategori: "Alat Dapur",
        item: "Piring",
        lowest_price: "Rp45.000",
        highest_price: "Rp180.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 24,
        id_kategori: 3,
        kategori: "Alat Dapur",
        item: "Gelas",
        lowest_price: "Rp22.000",
        highest_price: "Rp88.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 25,
        id_kategori: 3,
        kategori: "Alat Dapur",
        item: "Kompor",
        lowest_price: "Rp300.000",
        highest_price: "Rp1.200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 27,
        id_kategori: 3,
        kategori: "Alat Dapur",
        item: "Wajan",
        lowest_price: "Rp25.000",
        highest_price: "Rp100.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 28,
        id_kategori: 3,
        kategori: "Alat Dapur",
        item: "Panci",
        lowest_price: "Rp25.000",
        highest_price: "Rp100.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 29,
        id_kategori: 3,
        kategori: "Alat Dapur",
        item: "Rice Cooker",
        lowest_price: "Rp70.000",
        highest_price: "Rp290.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 30,
        id_kategori: 3,
        kategori: "Alat Dapur",
        item: "Talenan",
        lowest_price: "Rp5.000",
        highest_price: "Rp20.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 30,
        id_kategori: 3,
        kategori: "Alat Dapur",
        item: "Spatula",
        lowest_price: "Rp20.000",
        highest_price: "Rp80.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 31,
        id_kategori: 3,
        kategori: "Alat Dapur",
        item: "Sendok Sayur",
        lowest_price: "Rp20.000",
        highest_price: "Rp80.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 32,
        id_kategori: 3,
        kategori: "Alat Dapur",
        item: "Blender",
        lowest_price: "Rp300.000",
        highest_price: "Rp1.200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 33,
        id_kategori: 3,
        kategori: "Alat Dapur",
        item: "Gelas / sendok ukur",
        lowest_price: "Rp5.000",
        highest_price: "Rp20.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 34,
        id_kategori: 3,
        kategori: "Alat Dapur",
        item: "Saringan",
        lowest_price: "Rp5.000",
        highest_price: "Rp20.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 4,
    title: "Hardware",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 35,
        id_kategori: 4,
        kategori: "Komputer & Laptop",
        item: "Casing PC",
        lowest_price: "Rp679.000",
        highest_price: "Rp2.716.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 36,
        id_kategori: 4,
        kategori: "Komputer & Laptop",
        item: "Motherboard",
        lowest_price: "Rp405.000",
        highest_price: "Rp1.620.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 37,
        id_kategori: 4,
        kategori: "Komputer & Laptop",
        item: "RAM",
        lowest_price: "Rp238.000",
        highest_price: "Rp952.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 38,
        id_kategori: 4,
        kategori: "Komputer & Laptop",
        item: "ROM",
        lowest_price: "Rp156.000",
        highest_price: "Rp624.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 39,
        id_kategori: 4,
        kategori: "Komputer & Laptop",
        item: "GPU",
        lowest_price: "Rp800.000",
        highest_price: "Rp3.200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 40,
        id_kategori: 4,
        kategori: "Komputer & Laptop",
        item: "Power Supply",
        lowest_price: "Rp1.653.000",
        highest_price: "Rp6.612.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 41,
        id_kategori: 4,
        kategori: "Komputer & Laptop",
        item: "OS",
        lowest_price: "Rp150.000",
        highest_price: "Rp600.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 42,
        id_kategori: 4,
        kategori: "Komputer & Laptop",
        item: "Processor",
        lowest_price: "Rp950.000",
        highest_price: "Rp3.800.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 43,
        id_kategori: 4,
        kategori: "Komputer & Laptop",
        item: "Mouse",
        lowest_price: "Rp30.000",
        highest_price: "Rp120.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 44,
        id_kategori: 4,
        kategori: "Komputer & Laptop",
        item: "Keyboard",
        lowest_price: "Rp50.000",
        highest_price: "Rp200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 45,
        id_kategori: 4,
        kategori: "Komputer & Laptop",
        item: "Speaker",
        lowest_price: "Rp50.000",
        highest_price: "Rp200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 46,
        id_kategori: 4,
        kategori: "Komputer & Laptop",
        item: "Kipas laptop",
        lowest_price: "Rp100.000",
        highest_price: "Rp400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 47,
        id_kategori: 4,
        kategori: "Komputer & Laptop",
        item: "Webcam",
        lowest_price: "Rp100.000",
        highest_price: "Rp400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 48,
        id_kategori: 4,
        kategori: "Komputer & Laptop",
        item: "Hdd eksternal",
        lowest_price: "Rp500.000",
        highest_price: "Rp2.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 49,
        id_kategori: 4,
        kategori: "Komputer & Laptop",
        item: "Laptop / PC",
        lowest_price: "Rp8.000.000",
        highest_price: "Rp32.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 50,
        id_kategori: 4,
        kategori: "Komputer & Laptop",
        item: "Software",
        lowest_price: "Rp0",
        highest_price: "Rp0",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 51,
        id_kategori: 4,
        kategori: "Komputer & Laptop",
        item: "Stand laptop",
        lowest_price: "Rp100.000",
        highest_price: "Rp400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 5,
    title: "Interior & Tools Mobil",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 52,
        id_kategori: 5,
        kategori: "Interior & Tools Mobil",
        item: "Karpet Mobil",
        lowest_price: "Rp287.000",
        highest_price: "Rp1.108.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 53,
        id_kategori: 5,
        kategori: "Interior & Tools Mobil",
        item: "Charger USB",
        lowest_price: "Rp25.000",
        highest_price: "Rp100.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 54,
        id_kategori: 5,
        kategori: "Interior & Tools Mobil",
        item: "Pengharum Udara",
        lowest_price: "Rp18.000",
        highest_price: "Rp72.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 55,
        id_kategori: 5,
        kategori: "Interior & Tools Mobil",
        item: "Holder Hp",
        lowest_price: "Rp19.000",
        highest_price: "Rp76.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 56,
        id_kategori: 5,
        kategori: "Interior & Tools Mobil",
        item: "Bantal Jok",
        lowest_price: "Rp45.000",
        highest_price: "Rp180.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 57,
        id_kategori: 5,
        kategori: "Interior & Tools Mobil",
        item: "GPS",
        lowest_price: "Rp350.000",
        highest_price: "Rp1.400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 58,
        id_kategori: 5,
        kategori: "Interior & Tools Mobil",
        item: "Pompa roda portable",
        lowest_price: "Rp100.000",
        highest_price: "Rp400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 59,
        id_kategori: 5,
        kategori: "Interior & Tools Mobil",
        item: "Tyre Kit",
        lowest_price: "Rp300.000",
        highest_price: "Rp1.200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 60,
        id_kategori: 5,
        kategori: "Interior & Tools Mobil",
        item: "Kunci Sok Set",
        lowest_price: "Rp300.000",
        highest_price: "Rp1.200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 61,
        id_kategori: 5,
        kategori: "Interior & Tools Mobil",
        item: "Dongkrak",
        lowest_price: "Rp275.000",
        highest_price: "Rp1.060.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 62,
        id_kategori: 5,
        kategori: "Interior & Tools Mobil",
        item: "Obeng Set",
        lowest_price: "Rp50.000",
        highest_price: "Rp200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 6,
    title: "Gaming",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 63,
        id_kategori: 6,
        kategori: "Gaming Kit",
        item: "Monitor Gaming",
        lowest_price: "Rp1.700.000",
        highest_price: "Rp6.800.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 64,
        id_kategori: 6,
        kategori: "Gaming Kit",
        item: "Kursi Gaming",
        lowest_price: "Rp800.000",
        highest_price: "Rp3.200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 65,
        id_kategori: 6,
        kategori: "Gaming Kit",
        item: "Keyboard Gaming",
        lowest_price: "Rp800.000",
        highest_price: "Rp3.200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 66,
        id_kategori: 6,
        kategori: "Gaming Kit",
        item: "Mouse Gaming",
        lowest_price: "Rp500.000",
        highest_price: "Rp2.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 67,
        id_kategori: 6,
        kategori: "Gaming Kit",
        item: "Headset Gaming",
        lowest_price: "Rp500.000",
        highest_price: "Rp2.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 68,
        id_kategori: 6,
        kategori: "Gaming Kit",
        item: "Joystick / Controller",
        lowest_price: "Rp1.200.000",
        highest_price: "Rp4.800.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 69,
        id_kategori: 6,
        kategori: "Gaming Kit",
        item: "Mouse Pad",
        lowest_price: "Rp1.000.000",
        highest_price: "Rp4.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 70,
        id_kategori: 6,
        kategori: "Gaming Kit",
        item: "Speaker Gaming",
        lowest_price: "Rp900.000",
        highest_price: "Rp3.600.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 7,
    title: "Kamera",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 71,
        id_kategori: 7,
        kategori: "Fotografer Kit",
        item: "Kamera DSLR Pro level",
        lowest_price: "Rp4.900.000",
        highest_price: "Rp19.600.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 72,
        id_kategori: 7,
        kategori: "Fotografer Kit",
        item: "Variasi Lensa",
        lowest_price: "Rp1.300.000",
        highest_price: "Rp5.200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 73,
        id_kategori: 7,
        kategori: "Fotografer Kit",
        item: "Laptop / PC",
        lowest_price: "Rp8.000.000",
        highest_price: "Rp32.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 74,
        id_kategori: 7,
        kategori: "Fotografer Kit",
        item: "Hardisk Eksternal",
        lowest_price: "Rp500.000",
        highest_price: "Rp2.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 75,
        id_kategori: 7,
        kategori: "Fotografer Kit",
        item: "Filter Lensa",
        lowest_price: "Rp100.000",
        highest_price: "Rp400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 76,
        id_kategori: 7,
        kategori: "Fotografer Kit",
        item: "Background",
        lowest_price: "Rp100.000",
        highest_price: "Rp400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 77,
        id_kategori: 7,
        kategori: "Fotografer Kit",
        item: "Lampu Tambahan",
        lowest_price: "Rp100.000",
        highest_price: "Rp400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 78,
        id_kategori: 7,
        kategori: "Fotografer Kit",
        item: "Tripod",
        lowest_price: "Rp200.000",
        highest_price: "Rp800.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 79,
        id_kategori: 7,
        kategori: "Fotografer Kit",
        item: "Shutter Relese",
        lowest_price: "Rp350.000",
        highest_price: "Rp1.400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 80,
        id_kategori: 7,
        kategori: "Fotografer Kit",
        item: "Drone",
        lowest_price: "Rp2.500.000",
        highest_price: "Rp10.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 8,
    title: "Alat Musik",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 81,
        id_kategori: 8,
        kategori: "Gitar Akustik Kit",
        item: "Tuner",
        lowest_price: "Rp700.000",
        highest_price: "Rp2.800.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 82,
        id_kategori: 8,
        kategori: "Gitar Akustik Kit",
        item: "Pick",
        lowest_price: "Rp1.000.000",
        highest_price: "Rp4.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 83,
        id_kategori: 8,
        kategori: "Gitar Akustik Kit",
        item: "Tas GItar",
        lowest_price: "Rp800.000",
        highest_price: "Rp3.200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 84,
        id_kategori: 8,
        kategori: "Gitar Akustik Kit",
        item: "Capo",
        lowest_price: "Rp50.000",
        highest_price: "Rp200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 85,
        id_kategori: 8,
        kategori: "Gitar Akustik Kit",
        item: "Stand Gitar",
        lowest_price: "Rp150.000",
        highest_price: "Rp600.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 86,
        id_kategori: 8,
        kategori: "Gitar Akustik Kit",
        item: "Slider",
        lowest_price: "Rp50.000",
        highest_price: "Rp200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 9,
    title: "Videografi",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 87,
        id_kategori: 9,
        kategori: "Videografer Kit",
        item: "Microphone",
        lowest_price: "Rp700.000",
        highest_price: "Rp2.800.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 88,
        id_kategori: 9,
        kategori: "Videografer Kit",
        item: "Lampu Portabe",
        lowest_price: "Rp350.000",
        highest_price: "Rp1.400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 89,
        id_kategori: 9,
        kategori: "Videografer Kit",
        item: "Monitor Tambahan",
        lowest_price: "Rp1.900.000",
        highest_price: "Rp7.600.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 90,
        id_kategori: 9,
        kategori: "Videografer Kit",
        item: "Memori",
        lowest_price: "Rp95.000",
        highest_price: "Rp380.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 91,
        id_kategori: 9,
        kategori: "Videografer Kit",
        item: "Stabilizer",
        lowest_price: "Rp2.200.000",
        highest_price: "Rp8.800.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 92,
        id_kategori: 9,
        kategori: "Videografer Kit",
        item: "Tripod",
        lowest_price: "Rp240.000",
        highest_price: "Rp960.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 93,
        id_kategori: 9,
        kategori: "Videografer Kit",
        item: "Video track slider",
        lowest_price: "Rp3.500.000",
        highest_price: "Rp14.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 10,
    title: "Berenang",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 94,
        id_kategori: 10,
        kategori: "Diving Kit",
        item: "Mask",
        lowest_price: "Rp0",
        highest_price: "Rp0",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 95,
        id_kategori: 10,
        kategori: "Diving Kit",
        item: "Regulator",
        lowest_price: "Rp0",
        highest_price: "Rp0",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 96,
        id_kategori: 10,
        kategori: "Diving Kit",
        item: "Wetsuit dan Drysuit",
        lowest_price: "Rp0",
        highest_price: "Rp0",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 97,
        id_kategori: 10,
        kategori: "Diving Kit",
        item: "Weight Belt",
        lowest_price: "Rp0",
        highest_price: "Rp0",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 98,
        id_kategori: 10,
        kategori: "Diving Kit",
        item: "Fins",
        lowest_price: "Rp0",
        highest_price: "Rp0",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 99,
        id_kategori: 10,
        kategori: "Diving Kit",
        item: "Gauges",
        lowest_price: "Rp0",
        highest_price: "Rp0",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 100,
        id_kategori: 10,
        kategori: "Diving Kit",
        item: "Dive Computer",
        lowest_price: "Rp0",
        highest_price: "Rp0",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 101,
        id_kategori: 10,
        kategori: "Diving Kit",
        item: "Tabung Udara",
        lowest_price: "Rp0",
        highest_price: "Rp0",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 102,
        id_kategori: 10,
        kategori: "Diving Kit",
        item: "Torch",
        lowest_price: "Rp0",
        highest_price: "Rp0",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 11,
    title: "Alat Hiking",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 103,
        id_kategori: 11,
        kategori: "Hiking & Camp Kit",
        item: "Sepatu hiking",
        lowest_price: "Rp350.000",
        highest_price: "Rp1.400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 104,
        id_kategori: 11,
        kategori: "Hiking & Camp Kit",
        item: "Tas Gunung",
        lowest_price: "Rp450.000",
        highest_price: "Rp1.800.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 105,
        id_kategori: 11,
        kategori: "Hiking & Camp Kit",
        item: "Jas Hujan",
        lowest_price: "Rp100.000",
        highest_price: "Rp400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 106,
        id_kategori: 11,
        kategori: "Hiking & Camp Kit",
        item: "Sleeping Bag",
        lowest_price: "Rp180.000",
        highest_price: "Rp720.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 107,
        id_kategori: 11,
        kategori: "Hiking & Camp Kit",
        item: "Alat Serbaguna",
        lowest_price: "Rp0",
        highest_price: "Rp0",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 108,
        id_kategori: 11,
        kategori: "Hiking & Camp Kit",
        item: "Tenda",
        lowest_price: "Rp500.000",
        highest_price: "Rp2.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 109,
        id_kategori: 11,
        kategori: "Hiking & Camp Kit",
        item: "Matras",
        lowest_price: "Rp250.000",
        highest_price: "Rp1.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 110,
        id_kategori: 11,
        kategori: "Hiking & Camp Kit",
        item: "Peralatan Masak",
        lowest_price: "Rp200.000",
        highest_price: "Rp800.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 111,
        id_kategori: 11,
        kategori: "Hiking & Camp Kit",
        item: "Perlengkapan darurat",
        lowest_price: "Rp150.000",
        highest_price: "Rp600.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 12,
    title: "Peralatan Surfing",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 112,
        id_kategori: 12,
        kategori: "Surving Kit",
        item: "Board",
        lowest_price: "Rp0",
        highest_price: "Rp0",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 113,
        id_kategori: 12,
        kategori: "Surving Kit",
        item: "Rash Guard",
        lowest_price: "Rp0",
        highest_price: "Rp0",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 114,
        id_kategori: 12,
        kategori: "Surving Kit",
        item: "Board Short",
        lowest_price: "Rp0",
        highest_price: "Rp0",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 115,
        id_kategori: 12,
        kategori: "Surving Kit",
        item: "Leash",
        lowest_price: "Rp0",
        highest_price: "Rp0",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 116,
        id_kategori: 12,
        kategori: "Surving Kit",
        item: "Wax",
        lowest_price: "Rp90.000",
        highest_price: "Rp360.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 117,
        id_kategori: 12,
        kategori: "Surving Kit",
        item: "Wax Comb",
        lowest_price: "Rp150.000",
        highest_price: "Rp600.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 118,
        id_kategori: 12,
        kategori: "Surving Kit",
        item: "Fins",
        lowest_price: "Rp150.000",
        highest_price: "Rp600.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 119,
        id_kategori: 12,
        kategori: "Surving Kit",
        item: "Fins Key",
        lowest_price: "Rp75.000",
        highest_price: "Rp300.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 13,
    title: "Alat Berkebun",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 120,
        id_kategori: 13,
        kategori: "Berkebun Kit",
        item: "Sekop",
        lowest_price: "Rp25.000",
        highest_price: "Rp100.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 121,
        id_kategori: 13,
        kategori: "Berkebun Kit",
        item: "Cangkul",
        lowest_price: "Rp35.000",
        highest_price: "Rp140.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 122,
        id_kategori: 13,
        kategori: "Berkebun Kit",
        item: "Penggembur Tanah",
        lowest_price: "Rp35.000",
        highest_price: "Rp140.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 123,
        id_kategori: 13,
        kategori: "Berkebun Kit",
        item: "Sarung Tangan",
        lowest_price: "Rp5.000",
        highest_price: "Rp20.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 124,
        id_kategori: 13,
        kategori: "Berkebun Kit",
        item: "Sudip Tangan",
        lowest_price: "Rp0",
        highest_price: "Rp0",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 125,
        id_kategori: 13,
        kategori: "Berkebun Kit",
        item: "Selang",
        lowest_price: "Rp100.000",
        highest_price: "Rp400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 127,
        id_kategori: 13,
        kategori: "Berkebun Kit",
        item: "Penyiram",
        lowest_price: "Rp100.000",
        highest_price: "Rp400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 128,
        id_kategori: 13,
        kategori: "Berkebun Kit",
        item: "Semprotan",
        lowest_price: "Rp100.000",
        highest_price: "Rp400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 129,
        id_kategori: 13,
        kategori: "Berkebun Kit",
        item: "Gunting Tanaman",
        lowest_price: "Rp100.000",
        highest_price: "Rp400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 130,
        id_kategori: 13,
        kategori: "Berkebun Kit",
        item: "Pot Tanaman",
        lowest_price: "Rp100.000",
        highest_price: "Rp400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 14,
    title: "Serba Serbi Kue",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 130,
        id_kategori: 14,
        kategori: "Vesmat Kit",
        item: "Emblem Dasi Variasi",
        lowest_price: "Rp100.000",
        highest_price: "Rp400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 131,
        id_kategori: 14,
        kategori: "Vesmat Kit",
        item: "Crash Bar",
        lowest_price: "Rp100.000",
        highest_price: "Rp400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 132,
        id_kategori: 14,
        kategori: "Vesmat Kit",
        item: "Floormat Karpet",
        lowest_price: "Rp100.000",
        highest_price: "Rp400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 133,
        id_kategori: 14,
        kategori: "Vesmat Kit",
        item: "Stop Lamp Variasi",
        lowest_price: "Rp100.000",
        highest_price: "Rp400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 15,
    title: "Baby Care",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 134,
        id_kategori: 15,
        kategori: "Cooking Cake Kit",
        item: "Oven",
        lowest_price: "Rp200.000",
        highest_price: "Rp800.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 135,
        id_kategori: 15,
        kategori: "Cooking Cake Kit",
        item: "Pengocok Adonan",
        lowest_price: "Rp65.000",
        highest_price: "Rp270.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 136,
        id_kategori: 15,
        kategori: "Cooking Cake Kit",
        item: "Mixer",
        lowest_price: "Rp150.000",
        highest_price: "Rp600.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 137,
        id_kategori: 15,
        kategori: "Cooking Cake Kit",
        item: "Loyang",
        lowest_price: "Rp5.000",
        highest_price: "Rp20.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 138,
        id_kategori: 15,
        kategori: "Cooking Cake Kit",
        item: "Cetakan",
        lowest_price: "Rp6.000",
        highest_price: "Rp24.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 139,
        id_kategori: 15,
        kategori: "Cooking Cake Kit",
        item: "Wadah Adonan",
        lowest_price: "Rp5.000",
        highest_price: "Rp20.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 140,
        id_kategori: 15,
        kategori: "Cooking Cake Kit",
        item: "Timbangan",
        lowest_price: "Rp80.000",
        highest_price: "Rp320.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 141,
        id_kategori: 15,
        kategori: "Cooking Cake Kit",
        item: "Gelas Ukur",
        lowest_price: "Rp50.000",
        highest_price: "Rp200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 142,
        id_kategori: 15,
        kategori: "Cooking Cake Kit",
        item: "Oven Gas Deck Otomatis",
        lowest_price: "Rp13.700.000",
        highest_price: "Rp54.800.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 143,
        id_kategori: 15,
        kategori: "Cooking Cake Kit",
        item: "Oven Gas Convection",
        lowest_price: "Rp19.200.000",
        highest_price: "Rp76.800.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 144,
        id_kategori: 15,
        kategori: "Cooking Cake Kit",
        item: "Mesin Kukus/ Steamer",
        lowest_price: "Rp27.200.000",
        highest_price: "Rp104.800.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 145,
        id_kategori: 15,
        kategori: "Cooking Cake Kit",
        item: "Mixer Planetary",
        lowest_price: "Rp9.700.000",
        highest_price: "Rp38.800.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 146,
        id_kategori: 15,
        kategori: "Cooking Cake Kit",
        item: "Mixer Spiral",
        lowest_price: "Rp13.700.000",
        highest_price: "Rp54.800.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 147,
        id_kategori: 15,
        kategori: "Cooking Cake Kit",
        item: "Proofer / Mesin Pengembang Adonan",
        lowest_price: "Rp7.500.000",
        highest_price: "Rp30.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 148,
        id_kategori: 15,
        kategori: "Cooking Cake Kit",
        item: "Solid Rack Stainless Steel",
        lowest_price: "Rp6.500.000",
        highest_price: "Rp27.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 149,
        id_kategori: 15,
        kategori: "Cooking Cake Kit",
        item: "Troli Stainless Steel",
        lowest_price: "Rp4.500.000",
        highest_price: "Rp18.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 150,
        id_kategori: 15,
        kategori: "Cooking Cake Kit",
        item: "Meja Dough/ Meja Stainless For Bakery",
        lowest_price: "Rp3.500.000",
        highest_price: "Rp14.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 151,
        id_kategori: 15,
        kategori: "Cooking Cake Kit",
        item: "Wall Shelves Stainless",
        lowest_price: "Rp1.800.000",
        highest_price: "Rp7.200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 152,
        id_kategori: 15,
        kategori: "Cooking Cake Kit",
        item: "Loyang Stainless Steel",
        lowest_price: "Rp300.000",
        highest_price: "Rp1.200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 153,
        id_kategori: 15,
        kategori: "Cooking Cake Kit",
        item: "Loyang Alumunium",
        lowest_price: "Rp80.000",
        highest_price: "Rp320.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 154,
        id_kategori: 15,
        kategori: "Cooking Cake Kit",
        item: "Rak Loyang",
        lowest_price: "Rp2.700.000",
        highest_price: "Rp10.800.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 155,
        id_kategori: 15,
        kategori: "Cooking Cake Kit",
        item: "Hood/ Cerobong Asap",
        lowest_price: "Rp4.500.000",
        highest_price: "Rp18.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 156,
        id_kategori: 15,
        kategori: "Cooking Cake Kit",
        item: "Bain Marie Melted",
        lowest_price: "Rp6.500.000",
        highest_price: "Rp27.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 16,
    title: "Harga Property",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 157,
        id_kategori: 16,
        kategori: "Alat Listrik Rumah",
        item: "Testpen",
        lowest_price: "Rp10.000",
        highest_price: "Rp40.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 158,
        id_kategori: 16,
        kategori: "Alat Listrik Rumah",
        item: "Tang Potong",
        lowest_price: "Rp10.000",
        highest_price: "Rp40.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 159,
        id_kategori: 16,
        kategori: "Alat Listrik Rumah",
        item: "Tang Lancip",
        lowest_price: "Rp10.000",
        highest_price: "Rp40.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 160,
        id_kategori: 16,
        kategori: "Alat Listrik Rumah",
        item: "Tang Skun",
        lowest_price: "Rp10.000",
        highest_price: "Rp40.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 161,
        id_kategori: 16,
        kategori: "Alat Listrik Rumah",
        item: "Obeng + / -",
        lowest_price: "Rp10.000",
        highest_price: "Rp40.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 162,
        id_kategori: 16,
        kategori: "Alat Listrik Rumah",
        item: "Solder",
        lowest_price: "Rp10.000",
        highest_price: "Rp40.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 163,
        id_kategori: 16,
        kategori: "Alat Listrik Rumah",
        item: "Cutter",
        lowest_price: "Rp10.000",
        highest_price: "Rp40.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 164,
        id_kategori: 16,
        kategori: "Alat Listrik Rumah",
        item: "Multi Tester",
        lowest_price: "Rp10.000",
        highest_price: "Rp40.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 165,
        id_kategori: 16,
        kategori: "Alat Listrik Rumah",
        item: "Solasi",
        lowest_price: "Rp10.000",
        highest_price: "Rp40.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 17,
    title: "Inspirasi Kado",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 166,
        id_kategori: 17,
        kategori: "Kado Nikah Teman",
        item: "Album Foto Kenangan",
        lowest_price: "Rp15.000",
        highest_price: "Rp60.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 167,
        id_kategori: 17,
        kategori: "Kado Nikah Teman",
        item: "Peralatan Dapur",
        lowest_price: "Rp100.000",
        highest_price: "Rp400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 168,
        id_kategori: 17,
        kategori: "Kado Nikah Teman",
        item: "Parabotan Rumah Tangga",
        lowest_price: "Rp100.000",
        highest_price: "Rp400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 169,
        id_kategori: 17,
        kategori: "Kado Nikah Teman",
        item: "Barang Elektronik",
        lowest_price: "Rp100.000",
        highest_price: "Rp400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 170,
        id_kategori: 17,
        kategori: "Kado Nikah Teman",
        item: "Perlengkapan Kamar Mandi",
        lowest_price: "Rp100.000",
        highest_price: "Rp400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 18,
    title: "Inspirasi Kado",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 171,
        id_kategori: 18,
        kategori: "Programer Kit",
        item: "Kursi Gaming / Kerja",
        lowest_price: "Rp700.000",
        highest_price: "Rp2.800.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 172,
        id_kategori: 18,
        kategori: "Programer Kit",
        item: "Monitor Tambahan",
        lowest_price: "Rp1.500.000",
        highest_price: "Rp6.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 173,
        id_kategori: 18,
        kategori: "Programer Kit",
        item: "Kacamata Anti Radiasi",
        lowest_price: "Rp250.000",
        highest_price: "Rp1.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 174,
        id_kategori: 18,
        kategori: "Programer Kit",
        item: "Mouse",
        lowest_price: "Rp100.000",
        highest_price: "Rp400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 175,
        id_kategori: 18,
        kategori: "Programer Kit",
        item: "Software",
        lowest_price: "Rp0",
        highest_price: "Rp0",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 176,
        id_kategori: 18,
        kategori: "Programer Kit",
        item: "Headset",
        lowest_price: "Rp100.000",
        highest_price: "Rp400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 177,
        id_kategori: 18,
        kategori: "Programer Kit",
        item: "Laptop / PC",
        lowest_price: "Rp9.000.000",
        highest_price: "Rp36.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 19,
    title: "Inspirasi Kado",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 178,
        id_kategori: 19,
        kategori: "Harga Rumah Minimalis Jabodetabek",
        item: "Tipe 21",
        lowest_price: "Rp400.000.000",
        highest_price: "Rp1.600.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 179,
        id_kategori: 19,
        kategori: "Harga Rumah Minimalis Jabodetabek",
        item: "Tipe 36",
        lowest_price: "Rp800.000.000",
        highest_price: "Rp3.200.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 180,
        id_kategori: 19,
        kategori: "Harga Rumah Minimalis Jabodetabek",
        item: "Tipe 45",
        lowest_price: "Rp1.035.000.000",
        highest_price: "Rp4.140.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 181,
        id_kategori: 19,
        kategori: "Harga Rumah Minimalis Jabodetabek",
        item: "Tipe 54",
        lowest_price: "Rp18.000.000.000",
        highest_price: "Rp72.000.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 182,
        id_kategori: 19,
        kategori: "Harga Rumah Minimalis Jabodetabek",
        item: "Tipe 70",
        lowest_price: "Rp2.250.000.000",
        highest_price: "Rp9.000.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 20,
    title: "Inspirasi Kado",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 183,
        id_kategori: 20,
        kategori: "Baju favorit wanita",
        item: "Dress",
        lowest_price: "Rp50.000",
        highest_price: "Rp200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 184,
        id_kategori: 20,
        kategori: "Baju favorit wanita",
        item: "Kebaya",
        lowest_price: "Rp150.000",
        highest_price: "Rp600.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 185,
        id_kategori: 20,
        kategori: "Baju favorit wanita",
        item: "Jeans",
        lowest_price: "Rp65.000",
        highest_price: "Rp270.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 186,
        id_kategori: 20,
        kategori: "Baju favorit wanita",
        item: "Daleman",
        lowest_price: "Rp25.000",
        highest_price: "Rp100.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 187,
        id_kategori: 20,
        kategori: "Baju favorit wanita",
        item: "Hijab",
        lowest_price: "Rp30.000",
        highest_price: "Rp120.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 188,
        id_kategori: 20,
        kategori: "Baju favorit wanita",
        item: "Kaos",
        lowest_price: "Rp45.000",
        highest_price: "Rp180.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 189,
        id_kategori: 20,
        kategori: "Baju favorit wanita",
        item: "Daster",
        lowest_price: "Rp35.000",
        highest_price: "Rp140.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 21,
    title: "-",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 190,
        id_kategori: 21,
        kategori: "Baju favorit pria untuk wanita",
        item: "Tanktop",
        lowest_price: "Rp20.000",
        highest_price: "Rp80.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 191,
        id_kategori: 21,
        kategori: "Baju favorit pria untuk wanita",
        item: "Lingerie",
        lowest_price: "Rp45.000",
        highest_price: "Rp180.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 192,
        id_kategori: 21,
        kategori: "Baju favorit pria untuk wanita",
        item: "Pakaian tidur tipis",
        lowest_price: "Rp65.000",
        highest_price: "Rp270.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 193,
        id_kategori: 21,
        kategori: "Baju favorit pria untuk wanita",
        item: "Hotpans",
        lowest_price: "Rp35.000",
        highest_price: "Rp140.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 194,
        id_kategori: 21,
        kategori: "Baju favorit pria untuk wanita",
        item: "Rok mini",
        lowest_price: "Rp75.000",
        highest_price: "Rp300.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 195,
        id_kategori: 21,
        kategori: "Baju favorit pria untuk wanita",
        item: "Kemben",
        lowest_price: "Rp15.000",
        highest_price: "Rp60.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 196,
        id_kategori: 21,
        kategori: "Baju favorit pria untuk wanita",
        item: "Kostum jepang",
        lowest_price: "Rp95.000",
        highest_price: "Rp380.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 197,
        id_kategori: 21,
        kategori: "Baju favorit pria untuk wanita",
        item: "Kostum polisi",
        lowest_price: "Rp95.000",
        highest_price: "Rp380.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 198,
        id_kategori: 21,
        kategori: "Baju favorit pria untuk wanita",
        item: "Kostum suster",
        lowest_price: "Rp95.000",
        highest_price: "Rp380.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 199,
        id_kategori: 21,
        kategori: "Baju favorit pria untuk wanita",
        item: "Kostum cat woman",
        lowest_price: "Rp95.000",
        highest_price: "Rp380.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 200,
        id_kategori: 21,
        kategori: "Baju favorit pria untuk wanita",
        item: "Kostum hansip",
        lowest_price: "Rp95.000",
        highest_price: "Rp380.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 201,
        id_kategori: 21,
        kategori: "Baju favorit pria untuk wanita",
        item: "Kostum wonder woman",
        lowest_price: "Rp250.000",
        highest_price: "Rp1.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 22,
    title: "-",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 202,
        id_kategori: 22,
        kategori: "Korean Army kit",
        item: 'Kadobox 7-in-1 Set "BTS Army" A.R.M.Y Bundle Bangtan Boys Komplit',
        lowest_price: "Rp149.000",
        highest_price: "Rp596.000",
        reference_1:
          "https://shopee.co.id/Kadobox-7-in-1-Set-BTS-Army-A.R.M.Y-Bundle-Bangtan-Boys-Komplit-Merchandise-Murah-Kpop-Fans-BT21-i.131667889.4801172758?sp_atk=b13e3cff-7124-484c-9ba9-e5bb393c388c&xptdk=b13e3cff-7124-484c-9ba9-e5bb393c388c",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 203,
        id_kategori: 22,
        kategori: "Korean Army kit",
        item: "Cc-black PINK Standee Akrilik Standee Lisa Jennie Rose Figure Album",
        lowest_price: "Rp71.000",
        highest_price: "Rp294.000",
        reference_1:
          "https://shopee.co.id/Cc-black-PINK-Standee-Akrilik-Standee-Lisa-Jennie-Rose-Figure-Album-Foto-Indah-Ornamen-Dua-Sisi-Idola-Korea-Grup-BP-Stand-Sign-Dekorasi-Club-Fans-Hadiah-i.175751086.18067511450?sp_atk=891644ce-4a62-4c52-a6d0-f0e12a68445d&xptdk=891644ce-4a62-4c52-a6d0-f0e12a68445d",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 204,
        id_kategori: 22,
        kategori: "Korean Army kit",
        item: "KADOBOX BLACKPINK 7-in-1 BLINK Jennie Jisoo Lisa Rose - Koleksi Kpop Fans Sejati Penggemar BP Korea",
        lowest_price: "Rp194.000",
        highest_price: "Rp776.000",
        reference_1:
          "https://shopee.co.id/KADOBOX-BLACKPINK-7-in-1-BLINK-Jennie-Jisoo-Lisa-Rose-Koleksi-Kpop-Fans-Sejati-Penggemar-BP-Korea-i.131667889.6229034088?sp_atk=5c20754b-d236-42ee-ac7a-c8ef2af9d558&xptdk=5c20754b-d236-42ee-ac7a-c8ef2af9d558",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 23,
    title: "-",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 205,
        id_kategori: 23,
        kategori: "siap nikah cowo",
        item: "siap iman",
        lowest_price: "Rp0",
        highest_price: "Rp0",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 206,
        id_kategori: 23,
        kategori: "siap nikah cowo",
        item: "acara sederhana, tabungan hidup 6 bulan",
        lowest_price: "Rp70.000.000",
        highest_price: "Rp290.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 207,
        id_kategori: 23,
        kategori: "siap nikah cowo",
        item: "acara sederhana, tabungan hidup 6 bulan, rumah",
        lowest_price: "Rp200.000.000",
        highest_price: "Rp800.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 208,
        id_kategori: 23,
        kategori: "siap nikah cowo",
        item: "acara sederhana, tabungan hidup 6 bulan, hamil melahirkan",
        lowest_price: "Rp350.000.000",
        highest_price: "Rp1.400.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 209,
        id_kategori: 23,
        kategori: "siap nikah cowo",
        item: "acara sederhana, tabungan hidup 6 bulan, hamil melahirkan, sekolah sd anak",
        lowest_price: "Rp450.000.000",
        highest_price: "Rp1.800.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 210,
        id_kategori: 23,
        kategori: "siap nikah cowo",
        item: "mokondo",
        lowest_price: "Rp0",
        highest_price: "Rp0",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 24,
    title: "-",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 211,
        id_kategori: 24,
        kategori: "siap nikah cewe",
        item: "siap iman",
        lowest_price: "Rp0",
        highest_price: "Rp0",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 212,
        id_kategori: 24,
        kategori: "siap nikah cewe",
        item: "siap backup suami 12 bulan",
        lowest_price: "Rp36.000.000",
        highest_price: "Rp144.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 25,
    title: "-",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 213,
        id_kategori: 25,
        kategori: "paket pernikahan",
        item: "paket honey moon bandung",
        lowest_price: "Rp15.000.000",
        highest_price: "Rp60.000.000",
        reference_1: "http://konekelana.com/",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 214,
        id_kategori: 25,
        kategori: "paket pernikahan",
        item: "paket honey moon bali",
        lowest_price: "Rp25.000.000",
        highest_price: "Rp100.000.000",
        reference_1: "http://konekelana.com/",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 215,
        id_kategori: 25,
        kategori: "paket pernikahan",
        item: "paket honey moon turki",
        lowest_price: "Rp35.000.000",
        highest_price: "Rp140.000.000",
        reference_1: "http://konekelana.com/",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 216,
        id_kategori: 25,
        kategori: "paket pernikahan",
        item: "100 tamu nikahan di rumah",
        lowest_price: "Rp35.000.000",
        highest_price: "Rp140.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 217,
        id_kategori: 25,
        kategori: "paket pernikahan",
        item: "100 tamu nikahan di gedung atau venue pertemuan",
        lowest_price: "Rp70.000.000",
        highest_price: "Rp290.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 218,
        id_kategori: 25,
        kategori: "paket pernikahan",
        item: "100 tamu nikahan di resto",
        lowest_price: "Rp80.000.000",
        highest_price: "Rp320.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 219,
        id_kategori: 25,
        kategori: "paket pernikahan",
        item: "100 tamu nikahan di hotel",
        lowest_price: "Rp125.000.000",
        highest_price: "Rp500.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 26,
    title: "-",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 220,
        id_kategori: 26,
        kategori: "kado pacar",
        item: "liburan ke bali",
        lowest_price: "Rp8.000.000",
        highest_price: "Rp32.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 221,
        id_kategori: 26,
        kategori: "kado pacar",
        item: "barang kecil dan lucu di shopee",
        lowest_price: "Rp300.000",
        highest_price: "Rp1.200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 222,
        id_kategori: 26,
        kategori: "kado pacar",
        item: "anak",
        lowest_price: 10000000000000000,
        highest_price: 10000000000000000,
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 27,
    title: "-",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 223,
        id_kategori: 27,
        kategori: "kado anniv pernikahan",
        item: "bunga satu bouquet",
        lowest_price: "Rp50.000,00",
        highest_price: "Rp200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 224,
        id_kategori: 27,
        kategori: "kado anniv pernikahan",
        item: "perhiasan emas 10 gram",
        lowest_price: "Rp800.000",
        highest_price: "Rp3.200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 225,
        id_kategori: 27,
        kategori: "kado anniv pernikahan",
        item: "adopsi kucing",
        lowest_price: "Rp2.000.000",
        highest_price: "Rp8.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 28,
    title: "-",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 227,
        id_kategori: 28,
        kategori: "Kategori pacar sayang",
        item: "dinner romantis restoran",
        lowest_price: "Rp600.000",
        highest_price: "Rp2.400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 228,
        id_kategori: 28,
        kategori: "Kategori pacar sayang",
        item: "dinner romantis masak sendiri",
        lowest_price: "Rp300.000",
        highest_price: "Rp1.200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 229,
        id_kategori: 28,
        kategori: "Kategori pacar sayang",
        item: "nonton dan makan mingguan",
        lowest_price: "Rp250.000",
        highest_price: "Rp1.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 230,
        id_kategori: 28,
        kategori: "Kategori pacar sayang",
        item: "bunga satu bouquet",
        lowest_price: "Rp100.000",
        highest_price: "Rp400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 29,
    title: "-",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 230,
        id_kategori: 29,
        kategori: "Alat keamanan exlude surat dan izin",
        item: "G2 Premium Plus",
        lowest_price: "Rp35.000.000",
        highest_price: "Rp140.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 231,
        id_kategori: 29,
        kategori: "Alat keamanan exlude surat dan izin",
        item: "Ruger GP100",
        lowest_price: "Rp8.000.000",
        highest_price: "Rp32.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 232,
        id_kategori: 29,
        kategori: "Alat keamanan exlude surat dan izin",
        item: "Smith & Wesson S&W M&P Shield 9mm",
        lowest_price: "Rp13.200.000",
        highest_price: "Rp52.800.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 233,
        id_kategori: 29,
        kategori: "Alat keamanan exlude surat dan izin",
        item: "Browning Cynergy 20ga 27",
        lowest_price: "Rp25.000.000",
        highest_price: "Rp100.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 234,
        id_kategori: 29,
        kategori: "Alat keamanan exlude surat dan izin",
        item: "Pistol G2 Premium",
        lowest_price: "Rp35.000.000",
        highest_price: "Rp140.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 235,
        id_kategori: 29,
        kategori: "Alat keamanan exlude surat dan izin",
        item: "Senjata M4/M16",
        lowest_price: "Rp150.000.000",
        highest_price: "Rp600.000.000",
        reference_1: "sumber tidak diketahui",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 236,
        id_kategori: 29,
        kategori: "Alat keamanan exlude surat dan izin",
        item: "Biaya izin v1",
        lowest_price: "Rp100.000.000",
        highest_price: "Rp400.000.000",
        reference_1: "sumber tidak diketahui",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 237,
        id_kategori: 29,
        kategori: "Alat keamanan exlude surat dan izin",
        item: "Biaya izin v2",
        lowest_price: "Rp100.000.000",
        highest_price: "Rp400.000.000",
        reference_1:
          "https://lk2fhui.law.ui.ac.id/pembatasan-kepemilikan-senjata-api-oleh-masyarakat-sipil-dalam-perspektif-hukum-dan-sanksi-pidana-atas-penyalahgunaannya/#:~:text=Pasal%201%20ayat%20(1)%20UU,%2C%20menyimpan%2C%20mengangkut%2C%20menyembunyikan%2C",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 238,
        id_kategori: 29,
        kategori: "Alat keamanan exlude surat dan izin",
        item: "Biaya izin v3",
        lowest_price: "Rp100.000.000",
        highest_price: "Rp400.000.000",
        reference_1:
          "https://ombudsman.go.id/produk/lihat/286/SUB_OB_5cb8307f8ef70_file_20190529_092530.pdf",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
  {
    id: 30,
    title: "-",
    item: [
      {
        updated_at: "Des 25, 2022",
        no: 239,
        id_kategori: 30,
        kategori: "Biaya rumah tangga",
        item: "listrik 900 kwh",
        lowest_price: "Rp900.000",
        highest_price: "Rp3.600.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 240,
        id_kategori: 30,
        kategori: "Biaya rumah tangga",
        item: "listrik 5500 kwh",
        lowest_price: "Rp1.500.000",
        highest_price: "Rp6.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 241,
        id_kategori: 30,
        kategori: "Biaya rumah tangga",
        item: "makan masak sendiri perhari",
        lowest_price: "Rp50.000",
        highest_price: "Rp200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 242,
        id_kategori: 30,
        kategori: "Biaya rumah tangga",
        item: "belanja bulanan",
        lowest_price: "Rp800.000",
        highest_price: "Rp3.200.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 243,
        id_kategori: 30,
        kategori: "Biaya rumah tangga",
        item: "pagar rumah sedang",
        lowest_price: "Rp2.500.000",
        highest_price: "Rp10.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 244,
        id_kategori: 30,
        kategori: "Biaya rumah tangga",
        item: "tambah daya pln 900 ke 5500",
        lowest_price: "Rp3.500.000",
        highest_price: "Rp14.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 245,
        id_kategori: 30,
        kategori: "Biaya rumah tangga",
        item: "cat seluruh rumah kecil",
        lowest_price: "Rp350.000",
        highest_price: "Rp1.400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 246,
        id_kategori: 30,
        kategori: "Biaya rumah tangga",
        item: "gas hijau beli 3 kg",
        lowest_price: "Rp150.000",
        highest_price: "Rp600.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 247,
        id_kategori: 30,
        kategori: "Biaya rumah tangga",
        item: "gas pink beli 12 kg",
        lowest_price: "Rp350.000",
        highest_price: "Rp1.400.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 248,
        id_kategori: 30,
        kategori: "Biaya rumah tangga",
        item: "gas pink isi ulang 3 kg",
        lowest_price: "Rp30.000",
        highest_price: "Rp120.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 249,
        id_kategori: 30,
        kategori: "Biaya rumah tangga",
        item: "gas pink isi ulang 12 kg",
        lowest_price: "Rp150.000",
        highest_price: "Rp600.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 250,
        id_kategori: 30,
        kategori: "Biaya rumah tangga",
        item: "makeup istri skincare istri  - dandan biasa",
        lowest_price: "Rp500.000",
        highest_price: "Rp2.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 251,
        id_kategori: 30,
        kategori: "Biaya rumah tangga",
        item: "makeup istri skincare istri - dandan heboh",
        lowest_price: "Rp1.500.000",
        highest_price: "Rp6.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
      {
        updated_at: "Des 25, 2022",
        no: 252,
        id_kategori: 30,
        kategori: "Biaya rumah tangga",
        item: "renovasi kamar mandi",
        lowest_price: "Rp2.000.000",
        highest_price: "Rp8.000.000",
        reference_1: "",
        reference_2: "",
        reference_3: "",
      },
    ],
  },
];
