export const data_json = [
  {
    id: 1,
    title: "Pembersih",
    item: [
      {
        id: 1,
        kategori: "Pembersih",
        item: "Sapu Ijuk",
        harga: "-",
      },
      {
        id: 2,
        kategori: "Pembersih",
        item: "Pengki",
        harga: "-",
      },
      {
        id: 3,
        kategori: "Pembersih",
        item: "Kemoceng",
        harga: "-",
      },
      {
        id: 4,
        kategori: "Pembersih",
        item: "Sapu Lidi",
        harga: "-",
      },
      {
        id: 5,
        kategori: "Pembersih",
        item: "Sikat",
        harga: "-",
      },
      {
        id: 6,
        kategori: "Pembersih",
        item: "Kain Pel",
        harga: "-",
      },
      {
        id: 7,
        kategori: "Pembersih",
        item: "Tong Sampah",
        harga: "-",
      },
      {
        id: 8,
        kategori: "Pembersih",
        item: "Kanebo",
        harga: "-",
      },
    ],
  },
  {
    id: 2,
    title: "Tools Umum",
    item: [
      {
        id: 9,
        kategori: "Tools Umum",
        item: "Set Kunci L",
        harga: "-",
      },
      {
        id: 10,
        kategori: "Tools Umum",
        item: "Set Kunci Sok",
        harga: "-",
      },
      {
        id: 11,
        kategori: "Tools Umum",
        item: "Ring / Pas 12-14",
        harga: "-",
      },
      {
        id: 12,
        kategori: "Tools Umum",
        item: "Ring / Pas 8-10",
        harga: "-",
      },
      {
        id: 13,
        kategori: "Tools Umum",
        item: "Ring / Pas 17-19",
        harga: "-",
      },
      {
        id: 14,
        kategori: "Tools Umum",
        item: "Kunci Busi",
        harga: "-",
      },
      {
        id: 15,
        kategori: "Tools Umum",
        item: "Obeng +",
        harga: "-",
      },
      {
        id: 16,
        kategori: "Tools Umum",
        item: "Obeng -",
        harga: "-",
      },
      {
        id: 17,
        kategori: "Tools Umum",
        item: "Tang",
        harga: "-",
      },
      {
        id: 18,
        kategori: "Tools Umum",
        item: "Set Kunci Sok",
        harga: "-",
      },
      {
        id: 19,
        kategori: "Tools Umum",
        item: "Traker / Kunci Pully",
        harga: "-",
      },
      {
        id: 20,
        kategori: "Tools Umum",
        item: "Traker Penahan Pully",
        harga: "-",
      },
      {
        id: 21,
        kategori: "Tools Umum",
        item: "Obeng +",
        harga: "-",
      },
      {
        id: 22,
        kategori: "Tools Umum",
        item: "Obeng -",
        harga: "-",
      },
      {
        id: 23,
        kategori: "Tools Umum",
        item: "Testpen",
        harga: "-",
      },
      {
        id: 24,
        kategori: "Tools Umum",
        item: "Tang Potong",
        harga: "-",
      },
      {
        id: 25,
        kategori: "Tools Umum",
        item: "Tang Lancip",
        harga: "-",
      },
      {
        id: 26,
        kategori: "Tools Umum",
        item: "Tang Skun",
        harga: "-",
      },
      {
        id: 27,
        kategori: "Tools Umum",
        item: "Obeng + / -",
        harga: "-",
      },
      {
        id: 28,
        kategori: "Tools Umum",
        item: "Solder",
        harga: "-",
      },
      {
        id: 29,
        kategori: "Tools Umum",
        item: "Cutter",
        harga: "-",
      },
      {
        id: 30,
        kategori: "Tools Umum",
        item: "Multi Tester",
        harga: "-",
      },
      {
        id: 31,
        kategori: "Tools Umum",
        item: "Solasi",
        harga: "-",
      },
    ],
  },
  {
    id: 3,
    title: "Alat Dapur",
    item: [
      {
        id: 32,
        kategori: "Alat Dapur",
        item: "Talenan",
        harga: "-",
      },
      {
        id: 33,
        kategori: "Alat Dapur",
        item: "Spatula",
        harga: "-",
      },
      {
        id: 34,
        kategori: "Alat Dapur",
        item: "Sendok Sayur",
        harga: "-",
      },
      {
        id: 35,
        kategori: "Alat Dapur",
        item: "Blender",
        harga: "-",
      },
      {
        id: 36,
        kategori: "Alat Dapur",
        item: "Gelas / sendok ukur",
        harga: "-",
      },
      {
        id: 37,
        kategori: "Alat Dapur",
        item: "Saringan",
        harga: "-",
      },
    ],
  },
  {
    id: 4,
    title: "Hardware",
    item: [
      {
        id: 38,
        kategori: "Hardware",
        item: "Casing PC",
        harga: "-",
      },
      {
        id: 39,
        kategori: "Hardware",
        item: "Motherboard",
        harga: "-",
      },
      {
        id: 40,
        kategori: "Hardware",
        item: "Laptop / PC",
        harga: "",
      },
      {
        id: 41,
        kategori: "Hardware",
        item: "Kursi Gaming / Kerja",
        harga: "-",
      },
      {
        id: 42,
        kategori: "Hardware",
        item: "Monitor Tambahan",
        harga: "-",
      },
      {
        id: 43,
        kategori: "Hardware",
        item: "Kacamata Anti Radiasi",
        harga: "-",
      },
      {
        id: 44,
        kategori: "Hardware",
        item: "Mouse",
        harga: "-",
      },
      {
        id: 45,
        kategori: "Hardware",
        item: "Software",
        harga: "-",
      },
      {
        id: 46,
        kategori: "Hardware",
        item: "Headset",
        harga: "-",
      },
      {
        id: 47,
        kategori: "Hardware",
        item: "Mouse",
        harga: "-",
      },
      {
        id: 48,
        kategori: "Hardware",
        item: "Keyboard",
        harga: "-",
      },
      {
        id: 49,
        kategori: "Hardware",
        item: "Speaker",
        harga: "-",
      },

      {
        id: 50,
        kategori: "Hardware",
        item: "Kipas laptop",
        harga: "-",
      },
      {
        id: 51,
        kategori: "Hardware",
        item: "Webcam",
        harga: "-",
      },
      {
        id: 52,
        kategori: "Hardware",
        item: "Hdd eksternal",
        harga: "-",
      },
      {
        id: 53,
        kategori: "Hardware",
        item: "Stand laptop",
        harga: "-",
      },
      {
        id: 54,
        kategori: "Hardware",
        item: "Software",
        harga: "-",
      },
    ],
  },
  {
    id: 5,
    title: "Interior & Tools Mobil",
    item: [
      {
        id: 55,
        kategori: "Interior & Tools Mobil",
        item: "Pengharum Udara",
        harga: "-",
      },
      {
        id: 56,
        kategori: "Interior & Tools Mobil",
        item: "Holder Hp",
        harga: "-",
      },
      {
        id: 57,
        kategori: "Interior & Tools Mobil",
        item: "Bantal Jok",
        harga: "-",
      },
      {
        id: 58,
        kategori: "Interior & Tools Mobil",
        item: "GPS",
        harga: "-",
      },
      {
        id: 59,
        kategori: "Interior & Tools Mobil",
        item: "Pompa roda portable",
        harga: "-",
      },
      {
        id: 60,
        kategori: "Interior & Tools Mobil",
        item: "Tyre Kit",
        harga: "-",
      },
      {
        id: 61,
        kategori: "Interior & Tools Mobil",
        item: "Kunci Sok Set",
        harga: "-",
      },
      {
        id: 62,
        kategori: "Interior & Tools Mobil",
        item: "Dongkrak",
        harga: "-",
      },
      {
        id: 63,
        kategori: "Interior & Tools Mobil",
        item: "Obeng Set",
        harga: "-",
      },
    ],
  },
  {
    id: 6,
    title: "Gaming",
    item: [
      {
        id: 64,
        kategori: "Gaming",
        item: "Monitor Gaming",
        harga: "-",
      },
      {
        id: 65,
        kategori: "Gaming",
        item: "Kursi Gaming",
        harga: "-",
      },
      {
        id: 66,
        kategori: "Gaming",
        item: "Keyboard Gaming",
        harga: "-",
      },
      {
        id: 67,
        kategori: "Gaming",
        item: "Mouse Gaming",
        harga: "-",
      },
      {
        id: 68,
        kategori: "Gaming",
        item: "Headset Gaming",
        harga: "-",
      },
      {
        id: 69,
        kategori: "Gaming",
        item: "Joystick / Controller",
        harga: "-",
      },
      {
        id: 70,
        kategori: "Gaming",
        item: "Mouse Pad",
        harga: "-",
      },
      {
        id: 71,
        kategori: "Gaming",
        item: "Speaker Gaming",
        harga: "-",
      },
    ],
  },
  {
    id: 7,
    title: "Kamera",
    item: [
      {
        id: 72,
        kategori: "Kamera",
        item: "Kamera DSLR Pro level",
        harga: "-",
      },
      {
        id: 73,
        kategori: "Kamera",
        item: "Variasi Lensa",
        harga: "-",
      },
      {
        id: 74,
        kategori: "Kamera",
        item: "Hardisk Eksternal",
        harga: "-",
      },
      {
        id: 75,
        kategori: "Kamera",
        item: "Filter Lensa",
        harga: "-",
      },
      {
        id: 76,
        kategori: "Kamera",
        item: "Background",
        harga: "-",
      },
      {
        id: 77,
        kategori: "Kamera",
        item: "Lampu Tambahan",
        harga: "-",
      },
      {
        id: 78,
        kategori: "Kamera",
        item: "Tripod",
        harga: "-",
      },
      {
        id: 79,
        kategori: "Kamera",
        item: "Shutter Relese",
        harga: "-",
      },
      {
        id: 80,
        kategori: "Kamera",
        item: "Drone",
        harga: "-",
      },
    ],
  },
  {
    id: 8,
    title: "Alat Musik",
    item: [
      {
        id: 81,
        kategori: "Alat Musik",
        item: "Tuner",
        harga: "-",
      },
      {
        id: 82,
        kategori: "Alat Musik",
        item: "Pick",
        harga: "-",
      },
      {
        id: 83,
        kategori: "Alat Musik",
        item: "Tas GItar",
        harga: "-",
      },
      {
        id: 84,
        kategori: "Alat Musik",
        item: "Capo",
        harga: "-",
      },
      {
        id: 85,
        kategori: "Alat Musik",
        item: "Stand Gitar",
        harga: "-",
      },
      {
        id: 86,
        kategori: "Alat Musik",
        item: "Slider",
        harga: "-",
      },
    ],
  },
  {
    id: 9,
    title: "Videografi",
    item: [
      {
        id: 87,
        kategori: "Videografi",
        item: "Microphone",
        harga: "-",
      },
      {
        id: 88,
        kategori: "Videografi",
        item: "Lampu Portabe",
        harga: "-",
      },
      {
        id: 89,
        kategori: "Videografi",
        item: "Monitor Tambahan",
        harga: "-",
      },
      {
        id: 90,
        kategori: "Videografi",
        item: "Memori",
        harga: "-",
      },
      {
        id: 91,
        kategori: "Videografi",
        item: "Stabilizer",
        harga: "-",
      },
      {
        id: 92,
        kategori: "Videografi",
        item: "Tripod",
        harga: "-",
      },
      {
        id: 93,
        kategori: "Videografi",
        item: "Video track slider",
        harga: "-",
      },
    ],
  },
  {
    id: 10,
    title: "Berenang",
    item: [
      {
        id: 94,
        kategori: "Berenang",
        item: "Dive Computer",
        harga: "-",
      },
      {
        id: 95,
        kategori: "Berenang",
        item: "Tabung Udara",
        harga: "-",
      },
      {
        id: 96,
        kategori: "Berenang",
        item: "Torch",
        harga: "-",
      },
    ],
  },
  {
    id: 11,
    title: "Alat Hiking",
    item: [
      {
        id: 97,
        kategori: "Alat Hiking",
        item: "Sepatu hiking",
        harga: "-",
      },
      {
        id: 98,
        kategori: "Alat Hiking",
        item: "Tas Gunung",
        harga: "-",
      },
      {
        id: 99,
        kategori: "Alat Hiking",
        item: "Jas Hujan",
        harga: "-",
      },
      {
        id: 100,
        kategori: "Alat Hiking",
        item: "Sleeping Bag",
        harga: "-",
      },
      {
        id: 101,
        kategori: "Alat Hiking",
        item: "Alat Serbaguna",
        harga: "-",
      },
      {
        id: 102,
        kategori: "Alat Hiking",
        item: "Tenda",
        harga: "-",
      },
      {
        id: 103,
        kategori: "Alat Hiking",
        item: "Matras",
        harga: "-",
      },
      {
        id: 104,
        kategori: "Alat Hiking",
        item: "Peralatan Masak",
        harga: "-",
      },
      {
        id: 105,
        kategori: "Alat Hiking",
        item: "Perlengkapan darurat",
        harga: "-",
      },
    ],
  },
  {
    id: 12,
    title: "Peralatan Surfing",
    item: [
      {
        id: 106,
        kategori: "Peralatan Surfing",
        item: "Board",
        harga: "-",
      },
      {
        id: 107,
        kategori: "Peralatan Surfing",
        item: "Rash Guard",
        harga: "-",
      },
      {
        id: 108,
        kategori: "Peralatan Surfing",
        item: "Board Short",
        harga: "-",
      },
      {
        id: 109,
        kategori: "Peralatan Surfing",
        item: "Leash",
        harga: "-",
      },
      {
        id: 110,
        kategori: "Peralatan Surfing",
        item: "Wax",
        harga: "-",
      },
      {
        id: 111,
        kategori: "Peralatan Surfing",
        item: "Wax Comb",
        harga: "-",
      },
      {
        id: 112,
        kategori: "Peralatan Surfing",
        item: "Fins",
        harga: "-",
      },
      {
        id: 113,
        kategori: "Peralatan Surfing",
        item: "Fins Key",
        harga: "-",
      },
    ],
  },
  {
    id: 13,
    title: "Alat Berkebun",
    item: [
      {
        id: 114,
        kategori: "Alat Berkebun",
        item: "Sekop",
        harga: "-",
      },
      {
        id: 115,
        kategori: "Alat Berkebun",
        item: "Cangkul",
        harga: "-",
      },
      {
        id: 116,
        kategori: "Alat Berkebun",
        item: "Penggembur Tanah",
        harga: "-",
      },
      {
        id: 117,
        kategori: "Alat Berkebun",
        item: "Sarung Tangan",
        harga: "-",
      },
      {
        id: 118,
        kategori: "Alat Berkebun",
        item: "Sudip Tangan",
        harga: "-",
      },
      {
        id: 119,
        kategori: "Alat Berkebun",
        item: "Selang",
        harga: "-",
      },
      {
        id: 120,
        kategori: "Alat Berkebun",
        item: "Penyiram",
        harga: "-",
      },
      {
        id: 121,
        kategori: "Alat Berkebun",
        item: "Semprotan",
        harga: "-",
      },
      {
        id: 122,
        kategori: "Alat Berkebun",
        item: "Gunting Tanaman",
        harga: "-",
      },
      {
        id: 123,
        kategori: "Alat Berkebun",
        item: "Pot Tanaman",
        harga: "-",
      },
    ],
  },
  {
    id: 14,
    title: "Serba Serbi Kue",
    item: [
      {
        id: 124,
        kategori: "Serba Serbi Kue",
        item: "Oven",
        harga: "-",
      },
      {
        id: 125,
        kategori: "Serba Serbi Kue",
        item: "Pengocok Adonan",
        harga: "-",
      },
      {
        id: 126,
        kategori: "Serba Serbi Kue",
        item: "Mixer",
        harga: "-",
      },
      {
        id: 127,
        kategori: "Serba Serbi Kue",
        item: "Loyang",
        harga: "-",
      },
      {
        id: 128,
        kategori: "Serba Serbi Kue",
        item: "Cetakan",
        harga: "-",
      },
      {
        id: 129,
        kategori: "Serba Serbi Kue",
        item: "Wadah Adonan",
        harga: "-",
      },
      {
        id: 130,
        kategori: "Serba Serbi Kue",
        item: "Timbangan",
        harga: "-",
      },
      {
        id: 131,
        kategori: "Serba Serbi Kue",
        item: "Gelas Ukur",
        harga: "-",
      },
      {
        id: 132,
        kategori: "Serba Serbi Kue",
        item: "Penggiling",
        harga: "-",
      },
      {
        id: 133,
        kategori: "Serba Serbi Kue",
        item: "Oven Gas Deck Otomatis",
        harga: 13700000,
      },
      {
        id: 134,
        kategori: "Serba Serbi Kue",
        item: "Oven Gas Convection",
        harga: 19200000,
      },
      {
        id: 135,
        kategori: "Serba Serbi Kue",
        item: "Mesin Kukus/ Steamer",
        harga: 26200000,
      },
      {
        id: 136,
        kategori: "Serba Serbi Kue",
        item: "Mixer Planetary",
        harga: 9700000,
      },
      {
        id: 137,
        kategori: "Serba Serbi Kue",
        item: "Mixer Spiral",
        harga: 13700000,
      },
      {
        id: 138,
        kategori: "Serba Serbi Kue",
        item: "Proofer / Mesin Pengembang Adonan",
        harga: 7500000,
      },
      {
        id: 139,
        kategori: "Serba Serbi Kue",
        item: "Solid Rack Stainless Steel",
        harga: 6500000,
      },
      {
        id: 140,
        kategori: "Serba Serbi Kue",
        item: "Troli Stainless Steel",
        harga: 4500000,
      },
      {
        id: 141,
        kategori: "Serba Serbi Kue",
        item: "Meja Dough/ Meja Stainless For Bakery",
        harga: 3500000,
      },
      {
        id: 142,
        kategori: "Serba Serbi Kue",
        item: "Wall Shelves Stainless",
        harga: 1800000,
      },
      {
        id: 143,
        kategori: "Serba Serbi Kue",
        item: "Loyang Stainless Steel",
        harga: 300000,
      },
      {
        id: 144,
        kategori: "Serba Serbi Kue",
        item: "Loyang Alumunium",
        harga: 80000,
      },
      {
        id: 145,
        kategori: "Serba Serbi Kue",
        item: "Rak Loyang",
        harga: 2700000,
      },
      {
        id: 146,
        kategori: "Serba Serbi Kue",
        item: "Hood/ Cerobong Asap",
        harga: 4500000,
      },
      {
        id: 147,
        kategori: "Serba Serbi Kue",
        item: "Bain Marie Melted",
        harga: 6500000,
      },
      {
        id: 148,
        kategori: "Serba Serbi Kue",
        item: "Proofer / Mesin Pengembang Adonan",
        harga: 7500000,
      },
      {
        id: 149,
        kategori: "Serba Serbi Kue",
        item: "Solid Rack Stainless Steel",
        harga: 6500000,
      },
      {
        id: 150,
        kategori: "Serba Serbi Kue",
        item: "Troli Stainless Steel",
        harga: 4500000,
      },
      {
        id: 151,
        kategori: "Serba Serbi Kue",
        item: "Meja Dough/ Meja Stainless For Bakery",
        harga: 3500000,
      },
      {
        id: 152,
        kategori: "Serba Serbi Kue",
        item: "Wall Shelves Stainless",
        harga: 1800000,
      },
      {
        id: 153,
        kategori: "Serba Serbi Kue",
        item: "Loyang Stainless Steel",
        harga: 300000,
      },
      {
        id: 154,
        kategori: "Serba Serbi Kue",
        item: "Loyang Alumunium",
        harga: 80000,
      },
      {
        id: 155,
        kategori: "Serba Serbi Kue",
        item: "Rak Loyang",
        harga: 2700000,
      },
      {
        id: 156,
        kategori: "Serba Serbi Kue",
        item: "Hood/ Cerobong Asap",
        harga: 4500000,
      },
      {
        id: 157,
        kategori: "Serba Serbi Kue",
        item: "Bain Marie Melted",
        harga: 6500000,
      },
    ],
  },
  {
    id: 15,
    title: "Baby Care",
    item: [
      {
        id: 1,
        kategori: "Perlengkapan Bayi",
        item: "Popok",
        harga: "-",
      },
      {
        id: 2,
        kategori: "Perlengkapan Bayi",
        item: "Baju & Celana Bayi",
        harga: "-",
      },
      {
        id: 3,
        kategori: "Perlengkapan Bayi",
        item: "Kaus Kaki, Tangan & Topi",
        harga: "-",
      },
      {
        id: 4,
        kategori: "Perlengkapan Bayi",
        item: "Bedong Selimut",
        harga: "-",
      },
      {
        id: 5,
        kategori: "Perlengkapan Bayi",
        item: "Tempat Tidur bayi",
        harga: "-",
      },
      {
        id: 6,
        kategori: "Perlengkapan Bayi",
        item: "Perlak Bayi",
        harga: "-",
      },
      {
        id: 7,
        kategori: "Perlengkapan Bayi",
        item: "Kelambu",
        harga: "-",
      },
      {
        id: 8,
        kategori: "Perlengkapan Bayi",
        item: "Perlengkapan Mandi",
        harga: "-",
      },
    ],
  },
  {
    id: 16,
    title: "Harga Property",
    item: [
      {
        id: 163,
        kategori: "Harga Property",
        item: "Tipe 21",
        harga: "200 - 250 Jutaan",
      },
      {
        id: 164,
        kategori: "Harga Property",
        item: "Tipe 36",
        harga: "280 - 400 Jutaan",
      },
      {
        id: 165,
        kategori: "Harga Property",
        item: "Tipe 45",
        harga: "500 - 800 Jutaan",
      },
      {
        id: 166,
        kategori: "Harga Property",
        item: "Tipe 54",
        harga: "600 - 800 Jutaan",
      },
      {
        id: 167,
        kategori: "Harga Property",
        item: "Tipe 70",
        harga: "800 - 900 Jutaan",
      },
    ],
  },
  {
    id: 17,
    title: "Inspirasi Kado",
    item: [
      {
        id: 158,
        kategori: "Inspirasi Kado",
        item: "Album Foto Kenangan",
        harga: "-",
      },
      {
        id: 159,
        kategori: "Inspirasi Kado",
        item: "Peralatan Dapur",
        harga: "-",
      },
      {
        id: 160,
        kategori: "Inspirasi Kado",
        item: "Parabotan Rumah Tangga",
        harga: "-",
      },
      {
        id: 161,
        kategori: "Inspirasi Kado",
        item: "Barang Elektronik",
        harga: "-",
      },
      {
        id: 162,
        kategori: "Inspirasi Kado",
        item: "Perlengkapan Kamar Mandi",
        harga: "-",
      },
    ],
  },
];
